create crosswalks; save as internal data
geomarker-io/cincy pull request #6
Opened 2022-08-10 14:53 UTC by erikarasnick

2022-08-30 22:20 UTC, cole-brokamp requested changes
How are we envisioning that we will access these from within the CODEC tools?  Will they all be globally available once we `library(cincy)`?

Also, I think we should extend this pull request to include an example usage in `README.Rmd`.  This would help us think about how to best make them available within R code.

2022-08-30 22:20 UTC, cole-brokamp commented on data-raw/crosswalks/neighborhood_to_neighborhood.R
> +# lot of cases
was this left over from our discussion about neighborhood to neighborhood mappings?   we can delete this, right?

2022-08-30 22:20 UTC, cole-brokamp commented on data-raw/crosswalks/neighborhood_to_neighborhood.R
> +# lot of cases
also can remove the `.DS_Store` files (or add to `.gitignore`)

2022-08-31 13:14 UTC, erikarasnick commented
The way it is currently written, we would have to use the triple colon to access the crosswalk datasets. I think we had discussed keeping them internal data here, then using them in exported functions in CODECtools. I'm starting to think the crosswalks and the crosswalk functions should be in the same package... what do you think? Then the example of how to use the crosswalks would go in whichever package that is. It seems weird to me to keep the crosswalks here, write the crosswalk functions in CODECtools, and show their example use here.

2022-08-31 13:21 UTC, cole-brokamp commented
When I install from this branch, I can only see the following in the `:::` namespace:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/4367617/187688184-40cbe438-d33d-48fd-8bc2-447d22a5c856.png">

and I see this when trying to access them:

```r
r$> cincy::tract_to_zcta_2020
Error: 'tract_to_zcta_2020' is not an exported object from 'namespace:cincy'

r$> cincy:::tract_to_zcta_2020
Error: object 'tract_to_zcta_2020' not found

```

2022-08-31 13:23 UTC, cole-brokamp commented
But, I agree on making the functions and weights in the same package.  Let's keep working on this through this PR and then talk more tomorrow about where it should live long-term.

2022-08-31 13:29 UTC, erikarasnick commented
I know I ran the code for all the crosswalks, but somehow they didn't actually get stored in `sysdata.rda`. Now they should be accessible with the triple colon.

2022-09-01 14:34 UTC, cole-brokamp approved these changes

2022-09-01 14:34 UTC, merged